# Generated by Django 3.1.4 on 2020-12-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
