# Generated by Django 3.1.4 on 2020-12-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_auto_20201209_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
